### PR TITLE
Additon of `Django Snippets`

### PR DESCRIPTION
**Pull request by Lakshmikanth2001**
Django is a popular python web frame work  chekout this website [Django](https://www.djangoproject.com/)

- Added some snippets which can help in auto-completing some python functions and HTML text
- that's the reason `language` was not added to `package.json` entry

### CODE REVIEW

**Comment by ericsia** [comment]
@Lakshmikanth2001 i'm been busy this week. I'll check and merge it on monday

**Comment by Lakshmikanth2001** [comment]
Any updates?

**Comment by ericsia** [comment]
> Any updates?

Sorry our timezone maybe different, I should have mention the date directly. In your timezone it is next Monday of today. Meaning 4/June

**Comment by ericsia** [comment]
My laptop is broken in 1 of July after I unplug it 🤦‍♂️ not sure if it is caused my the cmos battery. I have to buy cmos battery online to ship it to here. But the good news is I still have a backup so I will bring it to campus on 4th July to use their pc and try to push the update as fast as I can

**Comment by ericsia** [comment]
awesome job @Lakshmikanth2001 I'm happy at this adding to Python Snippet. It makes it more complete that ever.

**Comment by ericsia** [comment]
@Lakshmikanth2001 I made little patch to the master, sync with the latest one when you are free. I have updated the changed to marketplace. Thanks again

**Pull request merged**
