### PR TITLE
Improvements in `pymysql` snippet and `datetime` snippet additon

### PR DESCRIPTION
**Pull request by Lakshmikanth2001**
- Improve `pymysql` Database class to run multiple SQL queries in a single `TCP` connection
 - Included `datetime` snippets form `timezone` conversion

### CODE REVIEW

**Comment by ericsia** [comment]
@Lakshmikanth2001 I will merge it after 1 week. Meanwhile if you spot a typo for this pr or you want to edit feel free do it

**Comment by Lakshmikanth2001** [comment]
ok take your time 😀

**Comment by Lakshmikanth2001** [comment]
Any Updates ?

**Comment by ericsia** [comment]
> Any Updates ?

no update from me 👍

**Comment by ericsia** [comment]
> Any Updates ?

I have published it now, good job as always 👍

**Pull request merged**
